# Generated by Django 4.0 on 2025-12-06 01:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='regular_holidays',
        ),
        migrations.AddField(
            model_name='shop',
            name='holidays_select',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mon', '月'), ('tue', '火'), ('wed', '水'), ('thu', '木'), ('fri', '金'), ('sat', '土'), ('sun', '日')], default='', max_length=30, verbose_name='固定定休日設定'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='holiday',
            field=models.TextField(blank=True, default='', verbose_name='定休日の案内詳細'),
        ),
        migrations.DeleteModel(
            name='Regular_holidays',
        ),
        migrations.DeleteModel(
            name='Weekday',
        ),
    ]
