# Generated by Django 4.0 on 2025-12-06 01:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_shop_regular_holidays_shop_holidays_select_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='holidays_select',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mon', '月'), ('tue', '火'), ('wed', '水'), ('thu', '木'), ('fri', '金'), ('sat', '土'), ('sun', '日')], default='', max_length=30, verbose_name='固定定休日設定'),
        ),
    ]
