# Generated by Django 4.0 on 2025-12-06 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_shop_holidays_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='特定休業日')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irregular_holidays', to='base.shop', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '特定休業日',
                'verbose_name_plural': '特定休業日設定',
                'unique_together': {('shop', 'date')},
            },
        ),
    ]
