# Generated by Django 4.0 on 2025-12-06 07:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_irregularholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='reserved_date',
            field=models.DateField(default=datetime.date(2025, 12, 6), verbose_name='予約日'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.shop', verbose_name='予約店舗'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user', verbose_name='予約ユーザー'),
        ),
    ]
