# Generated by Django 4.0 on 2025-12-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_reserve_reserved_date_alter_reserve_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserved_time',
            field=models.TimeField(verbose_name='予約日時'),
        ),
    ]
