# Generated by Django 4.0 on 2025-12-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_stripe_card_brand_user_stripe_card_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='canceled_at',
        ),
    ]
